language: go

go:
  - 1.7
  - 1.8
  - tip

before_install:
  # Install fontconfig library - phantomjs dependancy
  - sudo apt-get -qq update
  - sudo apt-get install -y fontconfig

install:
  - go get github.com/miekg/dns
  - go get -u github.com/jteeuwen/go-bindata/...

script: 
  - make test
