language: go

go:
  - 1.7
  - 1.8
  - tip

before_install:
  # Install fontconfig library - phantomjs dependancy
  - sudo apt-get -qq update
  - sudo apt-get install -y fontconfig

install:
  - go get github.com/miekg/dns

script: 
  - make test
